### PR TITLE
fix: wrap aiohttp sessions with 'async with' to ensure the session is cleaned up

### LINKED ISSUE #14: warning msg: Unclosed client session,  Unclosed connector
# Bug Report

## Describe the bug
I got this warning:
```txt
example one
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x105883820>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x1062769a0>, 0.497560541)]']
connector: <aiohttp.connector.TCPConnector object at 0x10626bfa0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x10626bfd0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x106276820>, 0.524557333)]']
connector: <aiohttp.connector.TCPConnector object at 0x10628c460>
created my-object object; etag: 5d41402abc4b2a76b9719d911017c592, version-id: 5868d1d6-5085-43b1-bb43-425fded2f2a4
```

## To Reproduce
My code is like this:
```python
import io
from miniopy_async import Minio
import asyncio

client = Minio(
        "play.min.io",
        access_key="Q3AM3UQ867SPQQA43P2F",
        secret_key="zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG",
    )


async def main():
    # Upload data.
    print('example one')
    result = await client.put_object(
        "test", "my-object", io.BytesIO(b"hello"), 5,
    )
    print(
        "created {0} object; etag: {1}, version-id: {2}".format(
            result.object_name, result.etag, result.version_id,
        ),
    )


if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
    loop.close()
```

## Expected behavior
I think the sesson or connection should be closed automatically, or some close api to use.

## Desktop:
 - OS: macos m1 pro
 - Version 13.0.1

### PR DESCRIPTION
**Pull request by nkukard**
This resolves #14.

To ensure the aiohttp client session is cleaned up properly we can wrap _url_open with an `async with`, it already accepts a session parameter so we can just pass it within the control block.

I did some testing with my app and I no longer receive the errors reported in #14.

### CODE REVIEW

**Comment by hlf20010508** [comment]
Thank you for your work.

I'm testing it right now.

**Comment by nkukard** [comment]
> Thank you for your work.
> 
> I'm testing it right now.

Awesome! thanks!

**Comment by hlf20010508** [comment]
So far your code works perfectly.

Let me do some more tests.

I think it'll be great.

**Comment by hlf20010508** [comment]
Something is wrong.

Try this:
```py
from miniopy_async import Minio
import asyncio

client = Minio(
    "play.min.io",
    access_key="Q3AM3UQ867SPQQA43P2F",
    secret_key="zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG",
    secure=True  # http for False, https for True
)

bucket_name = 'my-bucket'
test_file_name = 'testfile'

async def get_object():
    global bucket_name, test_file_name
    await client.fget_object(bucket_name, test_file_name, 'testfile')

async def main():
    print('Testing get object...')
    await get_object()

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
loop.close()
```

The `testfile` I've just uploaded is about 9MB, but I can only download the fist part of the file, which is just 4KB.

The reason is, in `fput_object`:
```py
response = await self.get_object(
                bucket_name,
                object_name,
                offset=offset,
                request_headers=request_headers,
                ssec=ssec,
                version_id=version_id,
                extra_query_params=extra_query_params,
            )
async with aiofile.async_open(tmp_file_path, "wb") as tmp_file:
                async for data in response.content.iter_chunked(n=1024 * 1024):
                    await tmp_file.write(data)
```

The file is divided into many parts, but the response has already closed, since in `put_object`'s return:
```py
return await self._execute(
            "GET",
            bucket_name,
            object_name,
            headers=headers,
            query_params=extra_query_params,
        )
```

So the response can only get the first part, and then because it has already close, we cannot get the rest of parts.

**Comment by hlf20010508** [comment]
I think we can just wrap the session outter.

Maybe pass the session to `_execute()` and let it pass to `_url_open`

**Comment by hlf20010508** [comment]
Ok, good news is, wrapping outter works fine in `fget_object`:
```py
response = None
        try:
            async with aiohttp.ClientSession() as session:
                response = await self.get_object(
                    bucket_name,
                    object_name,
                    offset=offset,
                    request_headers=request_headers,
                    ssec=ssec,
                    version_id=version_id,
                    extra_query_params=extra_query_params,
                    session=session
                )
                async with aiofile.async_open(tmp_file_path, "wb") as tmp_file:
                    async for data in response.content.iter_chunked(n=1024 * 1024):
                        await tmp_file.write(data)
                if os.path.exists(file_path):
                    os.remove(file_path)  # For windows compatibility.
                os.rename(tmp_file_path, file_path)
                return stat
        finally:
            pass
```

So this is a good solution.

Bad news is, there are so many functions that use `_execute()`, and maybe their referenced function has the same problem with `fget_object`.

So it takes a lot of time to fix and test.

The new release won't publish soon.

**Comment by hlf20010508** [comment]
I've done wrapping `self._execute()`.

Not all of them, only those with `response = self._execute()`.

Most of `return self._execute()` doesn't need it.

`api.Minio.select_object_content()` used `select.SelectObjectReader` which has some problem.

It seems in `select._read()` I cannot read data properly, `len(data)` almost never equal to `size`. I said ALMOST cause sometime it do equal. That made me so confused. The example code is in `examples/simple_examples/select_object_content.py`, you can have a look if you're interested in it.

I've created tests.py to test functions. So far some important functions have been tested and worked fine. But I need more time to test others.

**Comment by hlf20010508** [comment]
Ok I've tested all the function that I could.

So far so good.

Thank you for your solution, the problem has worried me for almost a year.

**Comment by hlf20010508** [comment]
I'm still checking that `select.SelectObjectReader` problem, later I'll merge this.

**Comment by Mkohl2508** [comment]
Hey, I have a question. Maybe I am wrong, but how do i get my content out of response from get_object(), if the client session is already closed, when you return the response object.

**Comment by hlf20010508** [comment]
> Hey, I have a question. Maybe I am wrong, but how do i get my content out of response from get_object(), if the client session is already closed, when you return the response object.

Yes, you're right. The solution is wrap it with session:
```py
async with aiohttp.ClientSession() as session:
    response = await client.get_object(bucket_name, object_name)
    response.text()
```

For now I don't know how to let it work without a wrap, so I'll update the example for it.

**Comment by hlf20010508** [comment]
Ok now `put_object` must have a `session` param.

**Comment by Mkohl2508** [comment]
Perfectly, thank you

**Pull request merged**
