### PR TITLE
allow aiohttp.ClientSession to be closed by a finalizer, during GC.

### PR DESCRIPTION
**Pull request by chasezheng**
Just so happen I run into this issue yesterday, and there is already a bug open (I see a slightly different issue but same root cause). I thought I could contribute. PTAL

### CODE REVIEW

**Comment by hlf20010508** [comment]
Thank you so much. I'll handle your pull requests.

**Review by hlf20010508 — COMMENTED** [review]
Why do you change `response_data = await response.text()` to `response_data = await response.content.read(10240)`

**Comment by chasezheng** [comment]
because response.text() can be quite large. Not really part of this issue, you can revert that, up to you.

**Comment by hlf20010508** [comment]
> because response.text() can be big. Not really part of this issue, you can revert that, up to you.

I just checked the source, and I think it's not necessary to offer a number
```py
async def read(self, n: int = -1) -> bytes:
        if self._exception is not None:
            raise self._exception

        # migration problem; with DataQueue you have to catch
        # EofStream exception, so common way is to run payload.read() inside
        # infinite loop. what can cause real infinite loop with StreamReader
        # lets keep this code one major release.
        if __debug__:
            if self._eof and not self._buffer:
                self._eof_counter = getattr(self, "_eof_counter", 0) + 1
                if self._eof_counter > 5:
                    internal_logger.warning(
                        "Multiple access to StreamReader in eof state, "
                        "might be infinite loop.",
                        stack_info=True,
                    )

        if not n:
            return b""

        if n < 0:
            # This used to just loop creating a new waiter hoping to
            # collect everything in self._buffer, but that would
            # deadlock if the subprocess sends more than self.limit
            # bytes.  So just call self.readany() until EOF.
            blocks = []
            while True:
                block = await self.readany()
                if not block:
                    break
                blocks.append(block)
            return b"".join(blocks)

        # TODO: should be `if` instead of `while`
        # because waiter maybe triggered on chunk end,
        # without feeding any data
        while not self._buffer and not self._eof:
            await self._wait("read")

        return self._read_nowait(n)
```

Let's use `response_data = await response.content.read()` instead.

**Comment by hlf20010508** [comment]
OK, please have a test in your project.
If everything works fine, I'll merge this pull request.

**Comment by chasezheng** [comment]
done. PTAL

**Comment by hlf20010508** [comment]
I don't know how to run the unit test, please help me.
Otherwise, everything looks fine.

**Comment by hlf20010508** [comment]
And I'm confused about `weakref.finalize`

Should I call it mannuly?

I mean what's the difference between
```py
weakref.finalizeres(
    asyncio.run_coroutine_threadsafe,
    session.close(),
    loop)
```
and
```py
weakref.finalizeres(
    asyncio.run_coroutine_threadsafe,
    session.close(),
    loop)()
```

They seems all looks fine in sanic, but the former one may occur this:
```
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7ff088eaed60>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7ff088eebfa0>, 8610173.525099183)]']
connector: <aiohttp.connector.TCPConnector object at 0x7ff088eaea60>
```
in simple example
```py
client = Minio(
    "play.min.io",
    access_key="Q3AM3UQ867SPQQA43P2F",
    secret_key="zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG",
    secure=True  # http for False, https for True
)

async def main():
    # Download data of an object.
    print("example one")
    await client.fget_object("my-bucket", "my-object", "my-filename")

asyncio.run(main())
```
but the later one won't.

It is not crucial because I think no one uses simple example in projects, but I want to know the reason. Please help me.

**Comment by chasezheng** [comment]
so with 
```python
finalizer = weakref.finalize(
  obj_to_gc,
  gc_func)
```
When you call `finalizer()`, that calls the `gc_func()` immediately. Otherwise `finalizer` will wait for `obj_to_gc` to be GC-ed, at which time, it will call `gc_func()` https://docs.python.org/3/library/weakref.html#weakref.finalize.__call__

In our case, we want to close the session when the response object is GC-ed.

I was running the test in Intellij, but in command line this works `python -m unittest discover -s tests/ -p '*.py'`. Sorry, could have made the command line simpler.

**Comment by hlf20010508** [comment]
Got it. Thank you so much.

**Pull request merged**
