### PR TITLE
Iterate properly if list_objects result is truncated

### PR DESCRIPTION
**Pull request by ponyisi**
Do not prematurely exit loop when retrieving list of objects in a bucket (addresses #26)

### CODE REVIEW

**Comment by hlf20010508** [comment]
Thanks for your PR.
[The original minio-py](https://github.com/minio/minio-py/blob/ffe9045fc8bdb435c02054336c79670ed61704a1/minio/api.py#L3050) doesn't have this issue.
I think I can try to convert it into async func.

**Comment by hlf20010508** [comment]
Ok, now `list_objects` can be used with `await` and `async for`.
```py
from miniopy_async import Minio
import asyncio

client = Minio(
    "play.min.io",
    access_key="Q3AM3UQ867SPQQA43P2F",
    secret_key="zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG",
    secure=True,  # http for False, https for True
)


async def main():
    async for objects in client.list_objects("many-object-bucket"):
        for obj in objects:
            print(obj)

    objects = await client.list_objects("many-object-bucket")
    print(len(objects))


asyncio.run(main())

```

**Comment by hlf20010508** [comment]
If no any other problem, I'll merge this PR.

**Comment by ponyisi** [comment]
Hi,

Thanks for the fast response. I have to admit that the `async for` interface seems extremely confusing to me (since it introduces two layers of iteration); is there any way that instead it could just return an iterator of objects, not an iterator of iterators of objects?

**Comment by hlf20010508** [comment]
Sorry, I've improved.
See my next commit.
```py
from miniopy_async import Minio
import asyncio

client = Minio(
    "play.min.io",
    access_key="Q3AM3UQ867SPQQA43P2F",
    secret_key="zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG",
    secure=True,  # http for False, https for True
)


async def main():
    async for object in client.list_objects("many-object-bucket"):
        print(object)

    objects = await client.list_objects("many-object-bucket")
    print(len(objects))


asyncio.run(main())
```

**Comment by hlf20010508** [comment]
Done.

**Comment by ponyisi** [comment]
Ok, I think this has the interface that we would like. Thank you!

**Comment by hlf20010508** [comment]
Published.

**Pull request merged**
